### ISSUE TITLE
Saving Whiteboard files / Prompt user to save Whiteboard

### ISSUE THREAD

**Issue by marshalhayes** [vtphan/Code4Brownies#1]
On **Ubuntu 16.04 LTS with Sublime Text v3**, Whiteboards shared from the Instructor automatically save in **~/.config/sublime-text-3/Packages/C4BStudent/Whiteboard/**

It would be preferable to either **(1)** prompt the user to specify a save location upon installation of C4BStudent, **(2)** automatically save the Whiteboard in the current working directory, **(3)** prompt the user to specify a save location on retrieving the Whiteboard, or **(4)** simply open the Whiteboard without saving so that the user can choose to save the file or not.

**Comment by vtphan** [comment]
Can you tell me the desirable objective is?   Is it you want to locate the whiteboard content, but it's already saved at a location where it's inconvenient navigate to?

(4) was previously the behavior, but I replaced it with the current behavior.  Unsaved content isn't highlighted with colors.

(2) seems reasonable, but I don't want to proliferate user space.

Whiteboard content is supposed to be temporary.  Students should copy and save the content to wherever they want.  But (2) seems to be a meaningful choice.

It'll be helpful if you can describe that the problems with the current behavior.

Thanks.

**Comment by vtphan** [comment]
New behavior: Automatically save the Whiteboard in the current working directory
